# Generated by Django 4.2.7 on 2024-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mightynovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.CharField(blank=True, default='Yuyuko', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(blank=True, default='Yuyuko Takemiya', max_length=100),
            preserve_default=False,
        ),
    ]
